name: _flutterfire_internals
description: A package hosting Dart code shared between FlutterFire plugins.
homepage: https://firebase.google.com/docs/firestore
repository: https://github.com/firebase/flutterfire/tree/main/packages/_flutterfire_internals
version: 1.3.42

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  collection: ^1.0.0
  firebase_core:
    path: ../firebase_core-3.4.1
  firebase_core_platform_interface:
    path: ../firebase_core_platform_interface-5.2.1
  flutter:
    sdk: flutter
  meta: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  test: any
