name: firebase_core_web
description: The web implementation of firebase_core
homepage: https://github.com/firebase/flutterfire/tree/main/packages/firebase_core/firebase_core_web
repository: https://github.com/firebase/flutterfire/tree/main/packages/firebase_core/firebase_core_web
version: 2.18.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  firebase_core_platform_interface:
    path: ../firebase_core_platform_interface-5.2.1
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.8.0
  web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseCoreWeb
        fileName: firebase_core_web.dart
