name: firebase_messaging_platform_interface
description: A common platform interface for the firebase_messaging plugin.
version: 4.5.44
homepage: https://github.com/firebase/flutterfire/tree/main/packages/firebase_messaging/firebase_messaging_platform_interface
repository: https://github.com/firebase/flutterfire/tree/main/packages/firebase_messaging/firebase_messaging_platform_interface

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  _flutterfire_internals:
    path: ../_flutterfire_internals-1.3.42
  firebase_core:
    path: ../firebase_core-3.4.1
  flutter:
    sdk: flutter
  meta: ^1.8.0
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  firebase_core_platform_interface:
    path: ../firebase_core_platform_interface-5.2.1
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
